### ISSUE TITLE
Upgrade to babel 6

### ISSUE THREAD

**Issue by nicolayr** [dhis2/app-management-app#10]
Since babel 5 is deprecated

**Comment by adhbh** [comment]
@nicolayr 
Please review this commit. Should i send the pull request?
https://github.com/adhbh/app-management-app/commit/d3d83b9f438d0d05f7a122fb31e88b28b2f4c62f

**Comment by nicolayr** [comment]
Looks good @adhbh - thank you!
I've merged your pull request locally and will push it soon.
