### ISSUE TITLE
Suggestion: Replace App Mgt icon with other artwork

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/app-management-app#20]
The App Management app icon looks a lot like the Apple App Store icon. The App Store icon has rules for how to use it, refer to https://developer.apple.com/app-store/marketing/guidelines/#appstore

I suggest that the current App Management app icon is replaced by an icon that is not under copyright.

![appmanagementicon](https://cloud.githubusercontent.com/assets/18207911/15710799/d8f49b8a-280b-11e6-8665-0a99d77ade01.png)
![appstoreicon](https://cloud.githubusercontent.com/assets/18207911/15710838/0ad67808-280c-11e6-9822-849c1b7d232a.png)

**Comment by ceciliapersson** [comment]
@nicolayr Any thoughts about this issue?

**Comment by nicolayr** [comment]
I simply re-used the icon from the old app management app. I'll be happy to replace it, but I don't have another icon sitting around so suggestions are welcome ;)

**Comment by ceciliapersson** [comment]
@nicolayr I see :) Thanks for your quick answer!

@larshelge, @Markionium Any ideas for another icon for the App Management app?

**Comment by ceciliapersson** [comment]
Maybe we could get some inspiration here: http://www.freepik.com/
