### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by nicolayr** [dhis2/app-management-app#24]
`npm run deploy`

**Comment by jason-p-pickering** [comment]
@nicolayr The .travis.yml file will not automate the deploy of master + v2X branches. `npm run deploy` could also be done, but as it is not, it will deploy to Sonatype. Is this correct? 

https://oss.sonatype.org/content/repositories/snapshots/org/hisp/dhis/dhis-app-app-management/2.25-SNAPSHOT/

**Comment by nicolayr** [comment]
`nvm run deploy` would just do `nvm run build && mvn clean deploy`. Since that's done by travis now, this issue is no longer relevant.
