### ISSUE TITLE
Duplicate apps menu

### ISSUE THREAD

**Issue by nicolayr** [dhis2/app-management-app#8]
The apps menu in the header bar is duplicated.

**Comment by adhbh** [comment]
@nicolayr https://github.com/adhbh/d2-ui/commit/3d4aa649e7537856a161f8d223193ea28b1cb7f5 My this commit fixes this issue. Should i send a pull request?

**Comment by Markionium** [comment]
@adhbh Yes sure thing, please go ahead an send a pull request.

We will be doing some additional work on the headerbar, but that is not started yet. So your solution will suffice :D

**Comment by adhbh** [comment]
@Markionium I have created a pull request for this temporary fix. :)

**Comment by nicolayr** [comment]
Unfortunately this doesn't seem to have fixed the issue.

The problem with this bug is that at least for me, it only happens when the app runs on a DHIS instance. Therefore it's hard to reproduce during development, and it's trickier than usual to figure out the root cause. This is made worse by the fact that it's currently tricky deploy new versions of front end apps to a local DHIS instance.

**Comment by Markionium** [comment]
A deploy isn't much more than unzipping a file though. So perhaps it's _good enough_ to just test it by copying the contents of the `build` folder straight into the correct location within tomcat. (If you use tomcat that is :P)

**Comment by nicolayr** [comment]
Fixed in deadffc7947020c9499b75d42b0a0d7b973c5f1e
